package cn.youai.ssm.po;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table item
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Item implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * 序列号
     * sequenceid
     */
    private Integer sequenceid;

    /**
     * id[17001-17100]
     * refId
     */
    private Integer refid;

    /**
     * 名称
     * name
     */
    private String name;

    /**
     * 大图id
     * imageId
     */
    private String imageid;

    /**
     * 小图id
     * iconId
     */
    private String iconid;

    /**
     * 简介
     * description
     */
    private String description;

    /**
     * 顺序[1-50]
     * sequence
     */
    private Integer sequence;

    /**
     * 货币类型1:元宝2:银币[1-2]
     * moneyType
     */
    private Integer moneytype;

    /**
     * 价格计算类型
     * priceCalculateType
     */
    private Integer pricecalculatetype;

    /**
     * 物品原价 [0-5000]
     * originalPrice
     */
    private Integer originalprice;

    /**
     * 折扣80:表示8折95:表示95折扣(两位数)[1-100]
     * discount
     */
    private Integer discount;

    /**
     * 限购次数(>=1:固定的可购买次数,0:不能在购买,-1:不限购,-2:根据vip等级决定)[-2~1000]
     * buyTimesLimit
     */
    private Integer buytimeslimit;

    /**
     * 道具效果
     * itemEffect
     */
    private String itemeffect;

    /**
     * VIP等级限制[0-10]
     * vipLevelLimit
     */
    private Integer viplevellimit;

    /**
     * 展现方式
     * propShowType
     */
    private Integer propshowtype;

    /**
     * 可显标识
     * visible
     */
    private Boolean visible;

    /**
     * 判断是不是宠物碎片,0为否,1为是
     * petFra
     */
    private Integer petfra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sequenceid
     *
     * @return the value of item.sequenceid
     *
     * @mbggenerated
     */
    public Integer getSequenceid() {
        return sequenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sequenceid
     *
     * @param sequenceid the value for item.sequenceid
     *
     * @mbggenerated
     */
    public void setSequenceid(Integer sequenceid) {
        this.sequenceid = sequenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.refId
     *
     * @return the value of item.refId
     *
     * @mbggenerated
     */
    public Integer getRefid() {
        return refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.refId
     *
     * @param refid the value for item.refId
     *
     * @mbggenerated
     */
    public void setRefid(Integer refid) {
        this.refid = refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.imageId
     *
     * @return the value of item.imageId
     *
     * @mbggenerated
     */
    public String getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.imageId
     *
     * @param imageid the value for item.imageId
     *
     * @mbggenerated
     */
    public void setImageid(String imageid) {
        this.imageid = imageid == null ? null : imageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.iconId
     *
     * @return the value of item.iconId
     *
     * @mbggenerated
     */
    public String getIconid() {
        return iconid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.iconId
     *
     * @param iconid the value for item.iconId
     *
     * @mbggenerated
     */
    public void setIconid(String iconid) {
        this.iconid = iconid == null ? null : iconid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.description
     *
     * @return the value of item.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.description
     *
     * @param description the value for item.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sequence
     *
     * @return the value of item.sequence
     *
     * @mbggenerated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sequence
     *
     * @param sequence the value for item.sequence
     *
     * @mbggenerated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.moneyType
     *
     * @return the value of item.moneyType
     *
     * @mbggenerated
     */
    public Integer getMoneytype() {
        return moneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.moneyType
     *
     * @param moneytype the value for item.moneyType
     *
     * @mbggenerated
     */
    public void setMoneytype(Integer moneytype) {
        this.moneytype = moneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.priceCalculateType
     *
     * @return the value of item.priceCalculateType
     *
     * @mbggenerated
     */
    public Integer getPricecalculatetype() {
        return pricecalculatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.priceCalculateType
     *
     * @param pricecalculatetype the value for item.priceCalculateType
     *
     * @mbggenerated
     */
    public void setPricecalculatetype(Integer pricecalculatetype) {
        this.pricecalculatetype = pricecalculatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.originalPrice
     *
     * @return the value of item.originalPrice
     *
     * @mbggenerated
     */
    public Integer getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.originalPrice
     *
     * @param originalprice the value for item.originalPrice
     *
     * @mbggenerated
     */
    public void setOriginalprice(Integer originalprice) {
        this.originalprice = originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.discount
     *
     * @return the value of item.discount
     *
     * @mbggenerated
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.discount
     *
     * @param discount the value for item.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.buyTimesLimit
     *
     * @return the value of item.buyTimesLimit
     *
     * @mbggenerated
     */
    public Integer getBuytimeslimit() {
        return buytimeslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.buyTimesLimit
     *
     * @param buytimeslimit the value for item.buyTimesLimit
     *
     * @mbggenerated
     */
    public void setBuytimeslimit(Integer buytimeslimit) {
        this.buytimeslimit = buytimeslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemEffect
     *
     * @return the value of item.itemEffect
     *
     * @mbggenerated
     */
    public String getItemeffect() {
        return itemeffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemEffect
     *
     * @param itemeffect the value for item.itemEffect
     *
     * @mbggenerated
     */
    public void setItemeffect(String itemeffect) {
        this.itemeffect = itemeffect == null ? null : itemeffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.vipLevelLimit
     *
     * @return the value of item.vipLevelLimit
     *
     * @mbggenerated
     */
    public Integer getViplevellimit() {
        return viplevellimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.vipLevelLimit
     *
     * @param viplevellimit the value for item.vipLevelLimit
     *
     * @mbggenerated
     */
    public void setViplevellimit(Integer viplevellimit) {
        this.viplevellimit = viplevellimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.propShowType
     *
     * @return the value of item.propShowType
     *
     * @mbggenerated
     */
    public Integer getPropshowtype() {
        return propshowtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.propShowType
     *
     * @param propshowtype the value for item.propShowType
     *
     * @mbggenerated
     */
    public void setPropshowtype(Integer propshowtype) {
        this.propshowtype = propshowtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.visible
     *
     * @return the value of item.visible
     *
     * @mbggenerated
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.visible
     *
     * @param visible the value for item.visible
     *
     * @mbggenerated
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.petFra
     *
     * @return the value of item.petFra
     *
     * @mbggenerated
     */
    public Integer getPetfra() {
        return petfra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.petFra
     *
     * @param petfra the value for item.petFra
     *
     * @mbggenerated
     */
    public void setPetfra(Integer petfra) {
        this.petfra = petfra;
    }

	@Override
	public String toString() {
		return "Item [sequenceid=" + sequenceid + ", refid=" + refid
				+ ", name=" + name + ", imageid=" + imageid + ", iconid="
				+ iconid + ", description=" + description + ", sequence="
				+ sequence + ", moneytype=" + moneytype
				+ ", pricecalculatetype=" + pricecalculatetype
				+ ", originalprice=" + originalprice + ", discount=" + discount
				+ ", buytimeslimit=" + buytimeslimit + ", itemeffect="
				+ itemeffect + ", viplevellimit=" + viplevellimit
				+ ", propshowtype=" + propshowtype + ", visible=" + visible
				+ ", petfra=" + petfra + "]";
	}
}