package cn.youai.ssm.po;

import java.io.Serializable;
import java.util.Date;

import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mon_reaward
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value="MonReaward",description="每日奖励物品")
public class MonReaward implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * id
     */
    private Integer id;

    /**
     * 日期奖励
     * date
     */
    @ApiModelProperty(dataType="date",value="奖励日期")
    private Date date;

    /**
     * 奖励物品
     * everyDayrewardMap
     */
    @ApiModelProperty(dataType="String",value="奖励物品")
    private String everydayrewardmap;
    

    private Integer type;
    
    private Integer daylimit;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_reaward.id
     *
     * @return the value of mon_reaward.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_reaward.id
     *
     * @param id the value for mon_reaward.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_reaward.date
     *
     * @return the value of mon_reaward.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_reaward.date
     *
     * @param date the value for mon_reaward.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_reaward.everyDayrewardMap
     *
     * @return the value of mon_reaward.everyDayrewardMap
     *
     * @mbggenerated
     */
    public String getEverydayrewardmap() {
        return everydayrewardmap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_reaward.everyDayrewardMap
     *
     * @param everydayrewardmap the value for mon_reaward.everyDayrewardMap
     *
     * @mbggenerated
     */
    public void setEverydayrewardmap(String everydayrewardmap) {
        this.everydayrewardmap = everydayrewardmap == null ? null : everydayrewardmap.trim();
    }

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getDaylimit() {
		return daylimit;
	}

	public void setDaylimit(Integer daylimit) {
		this.daylimit = daylimit;
	}

	@Override
	public String toString() {
		return "MonReaward [id=" + id + ", date=" + date
				+ ", everydayrewardmap=" + everydayrewardmap + ", type=" + type
				+ ", daylimit=" + daylimit + "]";
	}

	
}