package cn.youai.ssm.po;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table player_PropCodity
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PlayerPropcodity implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * pcId
     */
    private Integer pcid;

    /**
     * playerId
     */
    private Integer playerid;

    /**
     * id
     */
    private Integer id;

    /**
     * num
     */
    private Integer num;

    /**
     * 1商品 2 道具
     * type
     */
    private Integer type;
    /**
     * 当天已使用次数
     * useTimesToday
     */
    private Integer usetimestoday;

    /**
     * 当天已购买次数
     * buyTimesToday
     */
    private Integer buytimestoday;

    /**
     * 最后一次重置时间
     * lastResetTime
     */
    private Long lastresettime;

    /**
     * 获取途径 1购买 2签到 3其他
     * AcquType
     */
    private Integer acqutype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_PropCodity.pcId
     *
     * @return the value of player_PropCodity.pcId
     *
     * @mbggenerated
     */
    public Integer getPcid() {
        return pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_PropCodity.pcId
     *
     * @param pcid the value for player_PropCodity.pcId
     *
     * @mbggenerated
     */
    public void setPcid(Integer pcid) {
        this.pcid = pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_PropCodity.playerId
     *
     * @return the value of player_PropCodity.playerId
     *
     * @mbggenerated
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_PropCodity.playerId
     *
     * @param playerid the value for player_PropCodity.playerId
     *
     * @mbggenerated
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_PropCodity.id
     *
     * @return the value of player_PropCodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_PropCodity.id
     *
     * @param id the value for player_PropCodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_PropCodity.num
     *
     * @return the value of player_PropCodity.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_PropCodity.num
     *
     * @param num the value for player_PropCodity.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_PropCodity.type
     *
     * @return the value of player_PropCodity.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_PropCodity.type
     *
     * @param type the value for player_PropCodity.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
   
    
	public Integer getUsetimestoday() {
		return usetimestoday;
	}

	public void setUsetimestoday(Integer usetimestoday) {
		this.usetimestoday = usetimestoday;
	}

	public Integer getBuytimestoday() {
		return buytimestoday;
	}

	public void setBuytimestoday(Integer buytimestoday) {
		this.buytimestoday = buytimestoday;
	}

	public Long getLastresettime() {
		return lastresettime;
	}

	public void setLastresettime(Long lastresettime) {
		this.lastresettime = lastresettime;
	}

	public Integer getAcqutype() {
		return acqutype;
	}

	public void setAcqutype(Integer acqutype) {
		this.acqutype = acqutype;
	}

	@Override
	public String toString() {
		return "PlayerPropcodity [pcid=" + pcid + ", playerid=" + playerid
				+ ", id=" + id + ", num=" + num + ", type=" + type
				+ ", usetimestoday=" + usetimestoday + ", buytimestoday="
				+ buytimestoday + ", lastresettime=" + lastresettime
				+ ", acqutype=" + acqutype + "]";
	}

	
}