package cn.youai.ssm.po;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table player
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Player implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * 玩家编号
     * id
     */
    private Integer id;

    /**
     * 用户Id
     * userId
     */
    private Integer userid;

    /**
     * 玩家名称
     * name
     */
    private String name;

    /**
     * 性别(0女,1男)
     * gender
     */
    private Boolean gender;

    /**
     * 头像编号
     * imageId
     */
    private String imageid;

    /**
     * 级别
     * level
     */
    private Integer level;

    /**
     * 经验
     * crtExp
     */
    private Integer crtexp;

    /**
     * 体力
     * tiLi
     */
    private Integer tili;

    /**
     * 内力
     * neiLi
     */
    private Integer neili;

    /**
     * 最后一次计算体力
     * lastCalTiLiDate
     */
    private Long lastcaltilidate;

    /**
     * 最后一次计算内力
     * lastCalNeiLiDate
     */
    private Long lastcalneilidate;

    /**
     * 元宝
     * yuanBao
     */
    private Integer yuanbao;

    /**
     * 银两
     * yinLiang
     */
    private Integer yinliang;

    /**
     * 第一个侠客
     * firstCardHero
     */
    private Integer firstcardhero;

    /**
     * peaceEndDate
     */
    private Long peaceenddate;

    /**
     * resetBuyItemDate
     */
    private Long resetbuyitemdate;

    /**
     * lowerAtk
     */
    private Integer loweratk;

    /**
     * upperAtk
     */
    private Integer upperatk;

    /**
     * lowerDef
     */
    private Integer lowerdef;

    /**
     * upperDef
     */
    private Integer upperdef;

    /**
     * 玩家充值的总元宝数
     * voucherTotal
     */
    private Integer vouchertotal;

    /**
     * 个性签名
     * sign
     */
    private String sign;

    /**
     * 攻击力
     * power
     */
    private Integer power;

    /**
     * 语音介绍id，可以为空
     * voiceId
     */
    private String voiceid;

    /**
     * 背包容量
     * bagCapacity
     */
    private Integer bagcapacity;

    /**
     * 是否显示VIP
     * vipShow
     */
    private Boolean vipshow;

    /**
     * 上一次登录时间
     * loginTime
     */
    private Long logintime;

    /**
     * 铜钱
     * copper
     */
    private Integer copper;

    /**
     * 最后一次重置时间
     * lastResetTime
     */
    private Long lastresettime;

    /**
     * 仓库容量
     * repertoryCapacity
     */
    private Integer repertorycapacity;

    /**
     * 加密的playerId
     * secretPlayerId
     */
    private Long secretplayerid;

    /**
     * 专属头像框
     * PictureFrame
     */
    private String pictureframe;

    /**
     * vip等级
     * VIPLevel
     */
    private Integer viplevel;

    /**
     * 军团
     * juntuan
     */
    private Integer juntuan;

    /**
     * 称号
     * designation
     */
    private String designation;

    /**
     * 投诉人列表
     * complainantList
     */
    private String complainantlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.userId
     *
     * @return the value of player.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.userId
     *
     * @param userid the value for player.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.gender
     *
     * @return the value of player.gender
     *
     * @mbggenerated
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.gender
     *
     * @param gender the value for player.gender
     *
     * @mbggenerated
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.imageId
     *
     * @return the value of player.imageId
     *
     * @mbggenerated
     */
    public String getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.imageId
     *
     * @param imageid the value for player.imageId
     *
     * @mbggenerated
     */
    public void setImageid(String imageid) {
        this.imageid = imageid == null ? null : imageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.level
     *
     * @return the value of player.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.level
     *
     * @param level the value for player.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.crtExp
     *
     * @return the value of player.crtExp
     *
     * @mbggenerated
     */
    public Integer getCrtexp() {
        return crtexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.crtExp
     *
     * @param crtexp the value for player.crtExp
     *
     * @mbggenerated
     */
    public void setCrtexp(Integer crtexp) {
        this.crtexp = crtexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.tiLi
     *
     * @return the value of player.tiLi
     *
     * @mbggenerated
     */
    public Integer getTili() {
        return tili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.tiLi
     *
     * @param tili the value for player.tiLi
     *
     * @mbggenerated
     */
    public void setTili(Integer tili) {
        this.tili = tili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.neiLi
     *
     * @return the value of player.neiLi
     *
     * @mbggenerated
     */
    public Integer getNeili() {
        return neili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.neiLi
     *
     * @param neili the value for player.neiLi
     *
     * @mbggenerated
     */
    public void setNeili(Integer neili) {
        this.neili = neili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.lastCalTiLiDate
     *
     * @return the value of player.lastCalTiLiDate
     *
     * @mbggenerated
     */
    public Long getLastcaltilidate() {
        return lastcaltilidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.lastCalTiLiDate
     *
     * @param lastcaltilidate the value for player.lastCalTiLiDate
     *
     * @mbggenerated
     */
    public void setLastcaltilidate(Long lastcaltilidate) {
        this.lastcaltilidate = lastcaltilidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.lastCalNeiLiDate
     *
     * @return the value of player.lastCalNeiLiDate
     *
     * @mbggenerated
     */
    public Long getLastcalneilidate() {
        return lastcalneilidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.lastCalNeiLiDate
     *
     * @param lastcalneilidate the value for player.lastCalNeiLiDate
     *
     * @mbggenerated
     */
    public void setLastcalneilidate(Long lastcalneilidate) {
        this.lastcalneilidate = lastcalneilidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.yuanBao
     *
     * @return the value of player.yuanBao
     *
     * @mbggenerated
     */
    public Integer getYuanbao() {
        return yuanbao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.yuanBao
     *
     * @param yuanbao the value for player.yuanBao
     *
     * @mbggenerated
     */
    public void setYuanbao(Integer yuanbao) {
        this.yuanbao = yuanbao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.yinLiang
     *
     * @return the value of player.yinLiang
     *
     * @mbggenerated
     */
    public Integer getYinliang() {
        return yinliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.yinLiang
     *
     * @param yinliang the value for player.yinLiang
     *
     * @mbggenerated
     */
    public void setYinliang(Integer yinliang) {
        this.yinliang = yinliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.firstCardHero
     *
     * @return the value of player.firstCardHero
     *
     * @mbggenerated
     */
    public Integer getFirstcardhero() {
        return firstcardhero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.firstCardHero
     *
     * @param firstcardhero the value for player.firstCardHero
     *
     * @mbggenerated
     */
    public void setFirstcardhero(Integer firstcardhero) {
        this.firstcardhero = firstcardhero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.peaceEndDate
     *
     * @return the value of player.peaceEndDate
     *
     * @mbggenerated
     */
    public Long getPeaceenddate() {
        return peaceenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.peaceEndDate
     *
     * @param peaceenddate the value for player.peaceEndDate
     *
     * @mbggenerated
     */
    public void setPeaceenddate(Long peaceenddate) {
        this.peaceenddate = peaceenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.resetBuyItemDate
     *
     * @return the value of player.resetBuyItemDate
     *
     * @mbggenerated
     */
    public Long getResetbuyitemdate() {
        return resetbuyitemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.resetBuyItemDate
     *
     * @param resetbuyitemdate the value for player.resetBuyItemDate
     *
     * @mbggenerated
     */
    public void setResetbuyitemdate(Long resetbuyitemdate) {
        this.resetbuyitemdate = resetbuyitemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.lowerAtk
     *
     * @return the value of player.lowerAtk
     *
     * @mbggenerated
     */
    public Integer getLoweratk() {
        return loweratk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.lowerAtk
     *
     * @param loweratk the value for player.lowerAtk
     *
     * @mbggenerated
     */
    public void setLoweratk(Integer loweratk) {
        this.loweratk = loweratk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.upperAtk
     *
     * @return the value of player.upperAtk
     *
     * @mbggenerated
     */
    public Integer getUpperatk() {
        return upperatk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.upperAtk
     *
     * @param upperatk the value for player.upperAtk
     *
     * @mbggenerated
     */
    public void setUpperatk(Integer upperatk) {
        this.upperatk = upperatk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.lowerDef
     *
     * @return the value of player.lowerDef
     *
     * @mbggenerated
     */
    public Integer getLowerdef() {
        return lowerdef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.lowerDef
     *
     * @param lowerdef the value for player.lowerDef
     *
     * @mbggenerated
     */
    public void setLowerdef(Integer lowerdef) {
        this.lowerdef = lowerdef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.upperDef
     *
     * @return the value of player.upperDef
     *
     * @mbggenerated
     */
    public Integer getUpperdef() {
        return upperdef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.upperDef
     *
     * @param upperdef the value for player.upperDef
     *
     * @mbggenerated
     */
    public void setUpperdef(Integer upperdef) {
        this.upperdef = upperdef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.voucherTotal
     *
     * @return the value of player.voucherTotal
     *
     * @mbggenerated
     */
    public Integer getVouchertotal() {
        return vouchertotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.voucherTotal
     *
     * @param vouchertotal the value for player.voucherTotal
     *
     * @mbggenerated
     */
    public void setVouchertotal(Integer vouchertotal) {
        this.vouchertotal = vouchertotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.sign
     *
     * @return the value of player.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.sign
     *
     * @param sign the value for player.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.power
     *
     * @return the value of player.power
     *
     * @mbggenerated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.power
     *
     * @param power the value for player.power
     *
     * @mbggenerated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.voiceId
     *
     * @return the value of player.voiceId
     *
     * @mbggenerated
     */
    public String getVoiceid() {
        return voiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.voiceId
     *
     * @param voiceid the value for player.voiceId
     *
     * @mbggenerated
     */
    public void setVoiceid(String voiceid) {
        this.voiceid = voiceid == null ? null : voiceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.bagCapacity
     *
     * @return the value of player.bagCapacity
     *
     * @mbggenerated
     */
    public Integer getBagcapacity() {
        return bagcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.bagCapacity
     *
     * @param bagcapacity the value for player.bagCapacity
     *
     * @mbggenerated
     */
    public void setBagcapacity(Integer bagcapacity) {
        this.bagcapacity = bagcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.vipShow
     *
     * @return the value of player.vipShow
     *
     * @mbggenerated
     */
    public Boolean getVipshow() {
        return vipshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.vipShow
     *
     * @param vipshow the value for player.vipShow
     *
     * @mbggenerated
     */
    public void setVipshow(Boolean vipshow) {
        this.vipshow = vipshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.loginTime
     *
     * @return the value of player.loginTime
     *
     * @mbggenerated
     */
    public Long getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.loginTime
     *
     * @param logintime the value for player.loginTime
     *
     * @mbggenerated
     */
    public void setLogintime(Long logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.copper
     *
     * @return the value of player.copper
     *
     * @mbggenerated
     */
    public Integer getCopper() {
        return copper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.copper
     *
     * @param copper the value for player.copper
     *
     * @mbggenerated
     */
    public void setCopper(Integer copper) {
        this.copper = copper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.lastResetTime
     *
     * @return the value of player.lastResetTime
     *
     * @mbggenerated
     */
    public Long getLastresettime() {
        return lastresettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.lastResetTime
     *
     * @param lastresettime the value for player.lastResetTime
     *
     * @mbggenerated
     */
    public void setLastresettime(Long lastresettime) {
        this.lastresettime = lastresettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.repertoryCapacity
     *
     * @return the value of player.repertoryCapacity
     *
     * @mbggenerated
     */
    public Integer getRepertorycapacity() {
        return repertorycapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.repertoryCapacity
     *
     * @param repertorycapacity the value for player.repertoryCapacity
     *
     * @mbggenerated
     */
    public void setRepertorycapacity(Integer repertorycapacity) {
        this.repertorycapacity = repertorycapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.secretPlayerId
     *
     * @return the value of player.secretPlayerId
     *
     * @mbggenerated
     */
    public Long getSecretplayerid() {
        return secretplayerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.secretPlayerId
     *
     * @param secretplayerid the value for player.secretPlayerId
     *
     * @mbggenerated
     */
    public void setSecretplayerid(Long secretplayerid) {
        this.secretplayerid = secretplayerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.PictureFrame
     *
     * @return the value of player.PictureFrame
     *
     * @mbggenerated
     */
    public String getPictureframe() {
        return pictureframe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.PictureFrame
     *
     * @param pictureframe the value for player.PictureFrame
     *
     * @mbggenerated
     */
    public void setPictureframe(String pictureframe) {
        this.pictureframe = pictureframe == null ? null : pictureframe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.VIPLevel
     *
     * @return the value of player.VIPLevel
     *
     * @mbggenerated
     */
    public Integer getViplevel() {
        return viplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.VIPLevel
     *
     * @param viplevel the value for player.VIPLevel
     *
     * @mbggenerated
     */
    public void setViplevel(Integer viplevel) {
        this.viplevel = viplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.juntuan
     *
     * @return the value of player.juntuan
     *
     * @mbggenerated
     */
    public Integer getJuntuan() {
        return juntuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.juntuan
     *
     * @param juntuan the value for player.juntuan
     *
     * @mbggenerated
     */
    public void setJuntuan(Integer juntuan) {
        this.juntuan = juntuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.designation
     *
     * @return the value of player.designation
     *
     * @mbggenerated
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.designation
     *
     * @param designation the value for player.designation
     *
     * @mbggenerated
     */
    public void setDesignation(String designation) {
        this.designation = designation == null ? null : designation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.complainantList
     *
     * @return the value of player.complainantList
     *
     * @mbggenerated
     */
    public String getComplainantlist() {
        return complainantlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.complainantList
     *
     * @param complainantlist the value for player.complainantList
     *
     * @mbggenerated
     */
    public void setComplainantlist(String complainantlist) {
        this.complainantlist = complainantlist == null ? null : complainantlist.trim();
    }

	@Override
	public String toString() {
		return "Player [id=" + id + ", userid=" + userid + ", name=" + name
				+ ", gender=" + gender + ", imageid=" + imageid + ", level="
				+ level + ", crtexp=" + crtexp + ", tili=" + tili + ", neili="
				+ neili + ", lastcaltilidate=" + lastcaltilidate
				+ ", lastcalneilidate=" + lastcalneilidate + ", yuanbao="
				+ yuanbao + ", yinliang=" + yinliang + ", firstcardhero="
				+ firstcardhero + ", peaceenddate=" + peaceenddate
				+ ", resetbuyitemdate=" + resetbuyitemdate + ", loweratk="
				+ loweratk + ", upperatk=" + upperatk + ", lowerdef="
				+ lowerdef + ", upperdef=" + upperdef + ", vouchertotal="
				+ vouchertotal + ", sign=" + sign + ", power=" + power
				+ ", voiceid=" + voiceid + ", bagcapacity=" + bagcapacity
				+ ", vipshow=" + vipshow + ", logintime=" + logintime
				+ ", copper=" + copper + ", lastresettime=" + lastresettime
				+ ", repertorycapacity=" + repertorycapacity
				+ ", secretplayerid=" + secretplayerid + ", pictureframe="
				+ pictureframe + ", viplevel=" + viplevel + ", juntuan="
				+ juntuan + ", designation=" + designation
				+ ", complainantlist=" + complainantlist + "]";
	}
}