package cn.youai.ssm.po;

import java.io.Serializable;
import java.util.Date;

import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table player_everySingin
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value="PlayerEverysingin",description="玩家签到日期状态")
public class PlayerEverysingin implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * id
     */
    private Integer id;

    /**
     * 玩家id
     * playerID
     */
    @ApiModelProperty(dataType="int",value="玩家ID")
    private Integer playerid;

    /**
     * 签到日期
     * date
     */
    @ApiModelProperty(dataType="date",value="玩家签到日期")
    private Date date;

    /**
     * 签到状态1
     * issingin
     */
    @ApiModelProperty(dataType="int",value="是否领取1")
    private Integer issingin;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_everySingin.id
     *
     * @return the value of player_everySingin.id
     *
     * @mbggenerated
     */
    
    private int mType;
    
    private int dayLimit;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_everySingin.id
     *
     * @param id the value for player_everySingin.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_everySingin.playerID
     *
     * @return the value of player_everySingin.playerID
     *
     * @mbggenerated
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_everySingin.playerID
     *
     * @param playerid the value for player_everySingin.playerID
     *
     * @mbggenerated
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_everySingin.date
     *
     * @return the value of player_everySingin.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_everySingin.date
     *
     * @param date the value for player_everySingin.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_everySingin.issingin
     *
     * @return the value of player_everySingin.issingin
     *
     * @mbggenerated
     */
    public Integer getIssingin() {
        return issingin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_everySingin.issingin
     *
     * @param issingin the value for player_everySingin.issingin
     *
     * @mbggenerated
     */
    public void setIssingin(Integer issingin) {
        this.issingin = issingin;
    }

	public int getmType() {
		return mType;
	}

	public void setmType(int mType) {
		this.mType = mType;
	}

	public int getDayLimit() {
		return dayLimit;
	}

	public void setDayLimit(int dayLimit) {
		this.dayLimit = dayLimit;
	}

	@Override
	public String toString() {
		return "PlayerEverysingin [id=" + id + ", playerid=" + playerid
				+ ", date=" + date + ", issingin=" + issingin + ", mType="
				+ mType + ", dayLimit=" + dayLimit + "]";
	}

	
    
}